In [77]:
import numpy as np

In [78]:
mat = np.matrix([[0,1,2],[3,4,5]])

In [79]:
np.random.rand()

0.8817866345373799

In [80]:
x = np.random.rand(3)

In [81]:
y = np.random.rand(3)

In [82]:
xx = np.array([1,2,3])

In [83]:
yy = np.array([1,2,3])

In [84]:
matt1 = np.matrix([xx,])

In [85]:
matt2 = np.matrix([yy,])

In [86]:
matt1.T * matt2

matrix([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [89]:
xx.shape

(3,)

In [102]:
tt = np.array([1,2,3])
xx = np.matrix([tt,])
xx
for i in range(len(tt)-1):
    xx = np.insert(tt,tt.shape[0],tt,axis=0)




In [103]:
xx.reshape(3,2)

array([[1, 2],
       [3, 1],
       [2, 3]])

In [105]:
xx.reshape(1,6)

array([[1, 2, 3, 1, 2, 3]])